--Drop all FKeys
DECLARE @SQL varchar(4000)=''
SELECT @SQL = @SQL + 'ALTER TABLE ' + FK.TABLE_NAME + ' DROP CONSTRAINT [' + RTRIM(C.CONSTRAINT_NAME) +'];' + CHAR(13)
  FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
    ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
    ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
 INNER JOIN (
            SELECT i1.TABLE_NAME, i2.COLUMN_NAME
              FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
             INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2
                ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
            WHERE i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
           ) PT
    ON PT.TABLE_NAME = PK.TABLE_NAME
EXEC (@SQL)

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Staff_Lhm'))
BEGIN;
    DROP TABLE [Staff_Lhm];
END;

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Position_Lhm'))
BEGIN;
    DROP TABLE [Position_Lhm];
END;

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Staff'))
BEGIN;
    DROP TABLE [Staff];
END;

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Department'))
BEGIN;
    DROP TABLE [Department];
END;

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Position'))
BEGIN;
    DROP TABLE [Position];
END;